### ISSUE TITLE
time on the log file

### ISSUE THREAD

**Issue by EveWCheng** [OmegaLambda1998/InputFiles.jl#10]
Hey just thought it would be nice to have the date and time of when the log file is created on the top of the file :) thanks!

**Comment by OmegaLambda1998** [comment]
You can accomplish this in your code using the [Custom Metadata](https://www.omegalambda.au/BetterInputFiles.jl/dev/advanced/#Custom-Metadata) feature

```julia
using Dates

# Add key`TIME` to the `METADATA` dictionary, with the time this was run formatted as HH:MM
custom_metadata = [
    ("TIME",  Dates.format(now(), "HH:MM"))
]
input = setup_input(input_path, verbose; custome_metadata=custom_metadata)
```

**Comment by OmegaLambda1998** [comment]
Added TIME by default. Will be a few days before it is merged
